export const themes = {
    'Electric Blue': {
        primary: '#00F0FF',
        secondary: '#007A82',
        background: '#0D0D0D',
        card: '#1A1A1A',
        text: '#FFFFFF',
        textSecondary: '#A1A1AA',
        accent: '#00F0FF', // For backward compat or specific accents
    },
    'Lush Green': {
        primary: '#00FF94',
        secondary: '#00854D',
        background: '#051A10',
        card: '#0D261A',
        text: '#E0FFE0',
        textSecondary: '#8FB399',
        accent: '#00FF94',
    },
    'Crimson Pulse': {
        primary: '#FF2E4D',
        secondary: '#8F0014',
        background: '#1A0508',
        card: '#2E0D12',
        text: '#FFE0E5',
        textSecondary: '#B38085',
        accent: '#FF2E4D',
    },
    'Golden Hour': {
        primary: '#FFD700',
        secondary: '#B38600',
        background: '#1A1400',
        card: '#332900',
        text: '#FFFBE0',
        textSecondary: '#B3AC80',
        accent: '#FFD700',
    },
    'Royal Purple': {
        primary: '#bf00ff',
        secondary: '#66008F',
        background: '#0F001A',
        card: '#1F0033',
        text: '#F2E0FF',
        textSecondary: '#A680B3',
        accent: '#bf00ff',
    },
    'Obsidian': {
        primary: '#EDEDED',
        secondary: '#4D4D4D',
        background: '#000000',
        card: '#121212',
        text: '#FFFFFF',
        textSecondary: '#666666',
        accent: '#EDEDED',
    },
    'Clean Blue': {
        primary: '#2563EB',
        secondary: '#3B82F6',
        background: '#F8FAFC',
        card: '#FFFFFF',
        text: '#0F172A',
        textSecondary: '#64748B',
        accent: '#2563EB',
    },
};
